development:
  adapter: postgresql
  encoding: unicode
  database: mybrand_development
  hostname: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: mybrand_test
  hostname: localhost

